name:  lms app - image - build and push

on: push
jobs:
  push_to_registry:
    name: lms app - images push to repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      #- name: Build and push Docker image
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: Docker-images/
      #    push: true
      #    tags: dockerhub1233/lmsapp:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: python-images/
          push: true
          tags: dockerhub1233/lmsapp:v0.1.0